# Forward Kinematics service
string robot_name
float64[] qpos              # Joint positions to calculate FK for
string[] dof_names          # Optional: specific DOFs
string[] link_names         # Links to calculate poses for
---
bool success
string message
geometry_msgs/Point[] link_pos
geometry_msgs/Quaternion[] link_quat
