# Inverse Kinematics service
string robot_name
string target_link_name
geometry_msgs/Point position
geometry_msgs/Quaternion orientation
float64[] init_robot_pos        # Starting joint positions
bool request_joint_limit        # Respect joint limits
int32 max_samples               # random restarts
int32 max_solver_iterartions
float64 damping
float64 pos_tol                 # Position tolerance
float64 rot_tol                 # Rotation tolerance
bool[] pos_mask                 # [x, y, z] mask
bool[] rot_mask                 # [roll, pitch, yaw] mask
float64 max_step_size
int32[] dofs_idx_local          # DOFs to optimize
bool visualize                  # Show ghost robot in GUI
bool execute                    # Apply solution to robot
---
bool success                    # Service call status
bool solution_found             # If solver converged
float64[] joint_angles          # Resulting DOF positions
float64 target_pos_error
float64 target_quat_error
string message
