# Configure sensors for an entity
string entity
CameraOptions[] cameras
LidarOptions[] lidars
ImuOptions[] imus
ContactOptions[] contacts
ContactForceOptions[] contact_forces
---
simulation_interfaces/Result result
