sensors:
  # ----------------------------
  # CAMERA (RGB, Depth, etc.)
  # ----------------------------
  - name: front_cam
    sensor_type: cam
    ros_options:
      frame_id: lidar_link
      frequency: 50.0
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile
    attachment:
      link: lidar_link
      pos_offset: [0.0, 0.0, 0.0]
      euler_offset: [90.0, 0.0, -90.0]
    camera_types: [rgb, depth, segmentation, normal]
    res: [640, 480]
    fov: 30.0
    render_cfg:
      enable_textures: true
      enable_shadows: true
      enable_ambient_lighting: false
      enable_particles: true
      enable_backface_culling: true
      render_order: TILED
      tile_width: 32
      tile_height: 16
      max_range: 500.0
    light:
      top_light:
        direction: [0.0, 0.0, -1.0]
        enable_shadows: false
      front_light:
        direction: [0.0, -1.0, 0.0]
        enable_shadows: false
    add_noise: false
    noise_mean: 0.0
    noise_std: 0.01

  # # ----------------------------
  # # SECTIONAL LIDAR
  # # ----------------------------
  - name: sectional_lidar
    sensor_type: sectional_lidar  
    ros_options:
      frame_id: lidar_link
      frequency: 5.0
      topic: sectional_lidar_topic
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile  
    attachment:
      link: lidar_link
      pos_offset: [0.1, 0.0, 0.3]
      euler_offset: [0.0, 0.0, 0.0]
    fov: 90.0
    res: [256.0, 256.0]
    min_range: 0.5
    max_range: 10.0
    add_noise: false
    noise_mean: 0.0
    noise_std: 0.01
    log_points: true
    log_after_n_steps: 5
    log_point_color: [1.0,0.0,0.0]
    log_point_radius: 0.05
    log_rays: true
    log_ray_color: [1.0,0.0,0.0]
    log_ray_width: 0.05

  # # ----------------------------
  # # 3D LIDAR
  # # ----------------------------
  - name: lidar
    sensor_type: lidar
    ros_options:
      frame_id: lidar_link
      frequency: 10.0
      topic: lidar_topic
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile  
    attachment:
      link: lidar_link
      pos_offset: [0.0, 0.0, 0.5]
      euler_offset: [0.0, 0.0, 0.0]
    hfov: 360.0
    vfov: 30.0
    res: [256, 12]
    min_range: 0.3
    max_range: 100.0
    add_noise: false
    noise_mean: 0.0
    noise_std: 0.01
    log_points: true
    log_after_n_steps: 5
    log_point_color: [1.0,0.0,0.0]
    log_point_radius: 0.05
    log_rays: true
    log_ray_color: [1.0,0.0,0.0]
    log_ray_width: 0.05

  # # ----------------------------
  # # LASER SCAN
  # # ----------------------------
  - name: laser_scan
    sensor_type: laser_scan
    ros_options:
      frame_id: lidar_link
      frequency: 20.0
      topic: laser_scan_topic
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile  
    attachment:
      link: lidar_link
      pos_offset: [0.0, 0.0, 0.1]
      euler_offset: [0.0, 0.0, 0.0]
    fov: 360.0
    res: 720
    min_range: 0.3
    max_range: 50.0
    add_noise: false
    noise_mean: 0.0
    noise_std: 0.01
    log_points: true
    log_after_n_steps: 5
    log_point_color: [1.0,0.0,0.0]
    log_point_radius: 0.05
    log_rays: true
    log_ray_color: [1.0,0.0,0.0]
    log_ray_width: 0.05

  # # ----------------------------
  # # IMU
  # # ----------------------------
  - name: imu
    general_sensor_options:
      sensor_type: imu
      delay: 0.0
      update_ground_truth_only: false
      draw_debug: true
    ros_options:
      frame_id: base_link
      frequency: 100.0
      topic: imu_topic
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile  
    attachment:
      link: base_link
      pos_offset: [0.0, 0.0, 0.1]
      euler_offset: [0.0, 0.0, 0.0]

  # # ----------------------------
  # # CONTACT FORCE SENSOR
  # # ----------------------------
  - name: contact_force
    sensor_type: contact_force
    ros_options:
      frame_id: base_link
      frequency: 20.0
      topic: robot_one/contact_force
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile
    attachment:
      link: base_link

  # # ----------------------------
  # # CONTACT SENSOR
  # # ----------------------------
  - name: contact
    sensor_type: contact
    ros_options:
      frame_id: base_link
      frequency: 20.0
      topic: robot_one/contact
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile
    attachment:
      link: base_link